>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
>>> bg = BaseGeometry()

>>> bg2 = BaseGeometry("test")
Traceback (most recent call last):
TypeError: BaseGeometry() takes no arguments

>>> bg.area()
Traceback (most recent call last):
Exception: area() is not implemented

>>> bg.area(5)
Traceback (most recent call last):
TypeError: area() takes 1 positional argument but 2 were given

>>> bg.area(5, 5)
Traceback (most recent call last):
TypeError: area() takes 1 positional argument but 3 were given

>>> bg.integer_validator("my_int", 12)

>>> bg.integer_validator("width", 89)

>>> bg.integer_validator("name", "John")
Traceback (most recent call last):
TypeError: name must be an integer

>>> bg.integer_validator("age", 0)
Traceback (most recent call last):
ValueError: age must be greater than 0

>>> bg.integer_validator("distance", -4)
Traceback (most recent call last):
ValueError: distance must be greater than 0

>>> bg.integer_validator("height", True)
Traceback (most recent call last):
TypeError: height must be an integer

>>> bg.integer_validator("age", 5.0)
Traceback (most recent call last):
TypeError: age must be an integer

>>> bg.integer_validator("Name", None)
Traceback (most recent call last):
TypeError: Name must be an integer

>>> bg.integer_validator("testing", float('nan'))
Traceback (most recent call last):
TypeError: testing must be an integer

>>> bg.integer_validator("testing", float('inf'))
Traceback (most recent call last):
TypeError: testing must be an integer

>>> bg.integer_validator("name")
Traceback (most recent call last):
TypeError: integer_validator() missing 1 required positional argument: 'value'

>>> bg.integer_validator()
Traceback (most recent call last):
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

>>> bg.integer_validator("name", 1, 2)
Traceback (most recent call last):
TypeError: integer_validator() takes 3 positional arguments but 4 were given

>>> bg.integer_validator({"a": 1}, (1, 2))
Traceback (most recent call last):
TypeError: {'a': 1} must be an integer

>>> bg.integer_validator("test", [3])
Traceback (most recent call last):
TypeError: test must be an integer

>>> bg.integer_validator("test", (5,))
Traceback (most recent call last):
TypeError: test must be an integer

>>> bg.integer_validator("test", {1, 2})
Traceback (most recent call last):
TypeError: test must be an integer
